config/routes.rb
Rails.application.routes.draw do

 root 'pages#home'  

  get 'pages/home' ## by default created route,you can call it as like pages_home_path or :pages_home

  get 'pages/about' => 'pages#about', as: :About ## Must be call it as :About;about_path,:pages_about will not work in here,because we already declere it as :About

  get 'contact' => 'pages#contact' ## get route name as contact, see _nav.html.erb,we 

  

  get 'signup' => 'users#new'

  
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :name, :email

email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :name, :presence => true
					 :length => { :maximum => 11 }
    validates :email,:presence => true
    				 :format => { :with => email_regex }
    				 :uniqueness => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title= :Home
    #@active= :active
  	end

  def contact
  	@title= :Contact
  	#@active= :active
  	  end

  def about
  	@title= :About
  	#@active= :active
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@title = "Sign up"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title
		base_title="Ruby on Rails"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
			
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_css.html.erb
<%= stylesheet_link_tag 'bootstrap/css/bootstrap.min.css', :media => 'screen' %>
<%= stylesheet_link_tag 'bootstrap/css/bootstrap-responsive.min.css', :media => 'screen' %>
<%= stylesheet_link_tag 'styles.css', :media => 'screen' %>

app/views/layouts/_footer.html.erb
<hr/>
<div class="container-fluid"> 
<div class="row-fluid">
<footer>
       <p>Tanbir Hasan &copy; 2015</p>
</footer>
</div>

</div>

app/views/layouts/_js.html.erb
<%= javascript_include_tag 'jquery-1.9.1.min' %>
  <%= javascript_include_tag 'bootstrap/js/bootstrap.min' %>
  

app/views/layouts/_nav.html.erb
<div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href=<% :root %>>Admin Panel</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav pull-right">
                            <li class="dropdown">
                                <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"> <i class="icon-user"></i> Tanbir Hasan <i class="caret"></i>

                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a tabindex="-1" href="#">Profile</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a tabindex="-1" href="#">Logout</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav">
                            <li class="active">
                                
                                <%= link_to "Home", pages_home_path %>

                            </li>
                            <li class="">
                                <%= link_to "About", :About %>
                            </li>
                            <li class="">
                                
                                <%= link_to "Contact", contact_path %>
                            </li>
                            
                        </ul>
                    </div>
                    <!--/.nav-collapse -->
                </div>
            </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ruby on Rails | <%= @title %></title>
  <!--<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>-->
  <!--<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>-->
<%= render 'layouts/css' %>
<%= csrf_meta_tags %>
  
  
</head>
<body>
<%= render 'layouts/nav' %>
 
<div class="container-fluid">
<div class="row-fluid">
<%= yield %>
</div>
</div>
<%= render 'layouts/footer' %>
<%= render 'layouts/js' %>
</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
is a project to make a book and screencasts to teach web development
with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
is the sample application for the tutorial.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
Contact Ruby on Rails Tutorial about the sample app at the
<a href="http://railstutorial.org/feedback">feedback page</a>.
</p

app/views/pages/home.html.erb
<h1>Home Page</h1>
<p>
Hello This is my Home page.
<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
sample application.
</p>

<%= link_to "Sign up now!", :signup, :class => "btn btn-info" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>